export const products = [
    {
      id: 140,
      name: "Potential Damage",
      series: "",
      price: "Rp 10.625.000",
      category: "Acrylic on Canvas",
      artist: "Karyana Tri Utama",
      dimension: "130 X 110 cm",
      years: "2024",
      image: "/images/products/potential_damagec.png",
      isCart: false,
    },
    {
      id: 141,
      name: "Art Handler:",
      series: "Is THis A Work Of Art? (1/5)",
      price: "Rp 11.250.000",
      category: "Acrylic on Canvas",
      artist: "Karyana Tri Utama",
      dimension: "130 X 100 cm",
      years: "2023",
      image: "/images/products/art_handler1c.png",
      isCart: false,
    },
    {
      id: 142,
      name: "Memento Mori",
      series: "",
      price: "Rp 7.500.000",
      category: "Xenography and Augemented Reality on Paper",
      artist: "Wildan Ma'arief",
      dimension: "80 X 120 cm",
      years: "2024",
      image: "/images/products/memento_moric.png",
      isCart: false,
    },
    {
      id: 143,
      name: "Siapa Diriku, Oh, Sayangku?",
      series: "",
      price: "Rp 10.000.000",
      category: "Rubbercut and Offset Ink on Mirror",
      artist: "Wildan Ma'arief",
      dimension: "100 X 90 cm",
      years: "2023",
      image: "/images/products/sdosc.png",
      isCart: false,
    },
    {
      id: 132,
      name: "14/24",
      series: "",
      price: "Rp 15.625.000",
      category: "Mix Media on Canvas",
      artist: "Muhammad Rasyid Salahuddin",
      dimension: "100 X 100 cm",
      years: "2023",
      image: "/images/products/1424c.png",
      isCart: false,
    },
    {
      id: 133,
      name: "Kapan akan Sampai/akan Sampai Kapan",
      series: "",
      price: "Rp 15.625.000",
      category: "Mix Media on Canvas",
      artist: "Muhammad Rasyid Salahuddin",
      dimension: "100 X 100 cm",
      years: "2024",
      image: "/images/products/kasaskc.png",
      isCart: false,
    },
    {
      id: 134,
      name: "Sekelibat",
      series: "",
      price: "Rp 6.250.000",
      category: "Oil on Canvas",
      artist: "Muhammad Rasyid Salahuddin",
      dimension: "80 X 90 cm",
      years: "2023",
      image: "/images/products/sekelibatc.png",
      isCart: false,
    },
    {
      id: 135,
      name: "Apa Benar?",
      series: "",
      price: "Rp 15.625.000",
      category: "Mix Media on Canvas",
      artist: "Muhammad Rasyid Salahuddin",
      dimension: "70 X 170 cm",
      years: "2023",
      image: "/images/products/apa_benarc.png",
      isCart: false,
    },
    {
      id: 136,
      name: "Kini, Esok dan Nanti",
      series: "",
      price: "Rp 6.250.000",
      category: "Mix Media on Canvas",
      artist: "Muhammad Rasyid Salahuddin",
      dimension: "60 X 80 cm",
      years: "2023",
      image: "/images/products/kenc.png",
      isCart: false,
    },
    {
      id: 137,
      name: "Musim Kain",
      series: "",
      price: "Rp 9.375.000",
      category: "Acrylic on Canvas",
      artist: "Shalza Fitri",
      dimension: "140 X 60 cm",
      years: "2023",
      image: "/images/products/mkc.png",
      isCart: false,
    },
    {
      id: 138,
      name: "Musin Rindu",
      series: "",
      price: "Rp 8.125.000",
      category: "Acrylic on Canvas",
      artist: "Shalza Fitri",
      dimension: "140 X 60 cm",
      years: "2023",
      image: "/images/products/mrc.png",
      isCart: false,
    },
    {
      id: 139,
      name: "Dad's Last Money",
      series: "",
      price: "Rp 6.875.000",
      category: "Acrylic on Canvas",
      artist: "Shalza Fitri",
      dimension: "150 X 50 cm",
      years: "2024",
      image: "/images/products/dlmc.png",
      isCart: false,
    },
    {
      id: 125,
      name: "Kalut",
      series: "",
      price: "Rp ",
      category: "Acrylic on Canvas",
      artist: "Aura Paramaratri",
      dimension: "140 X 90 cm",
      years: "2024",
      image: "/images/products/kalutc.png",
      isCart: false,
    },
    {
      id: 126,
      name: "Kalang",
      series: "",
      price: "Rp ",
      category: "Mix Media",
      artist: "Aura Paramaratri",
      dimension: "30 X 30 cm",
      years: "2024",
      image: "/images/products/kalangc.png",
      isCart: false,
    },
    {
      id: 127,
      name: "Kelir",
      series: "",
      price: "Rp ",
      category: "Acrylic on Canvas",
      artist: "Aura Paramaratri",
      dimension: "50 X 60 cm",
      years: "2023",
      image: "/images/products/kelirc.png",
      isCart: false,
    },
    {
      id: 128,
      name: "Samsara",
      series: "",
      price: "Rp ",
      category: "Acrylic on Canvas",
      artist: "Aura Paramaratri",
      dimension: "50 X 60 cm",
      years: "2023",
      image: "/images/products/samsarac.png",
      isCart: false,
    },
    {
      id: 129,
      name: "Banyu",
      series: "",
      price: "Rp ",
      category: "Acrylic on Canvas",
      artist: "Aura Paramaratri",
      dimension: "50 X 60 cm",
      years: "2023",
      image: "/images/products/banyuc.png",
      isCart: false,
    },
    {
      id: 130,
      name: "Gulita",
      series: "",
      price: "Rp ",
      category: "Acrylic on Canvas",
      artist: "Aura Paramaratri",
      dimension: "50 X 60 cm",
      years: "2023",
      image: "/images/products/gulitac.png",
      isCart: false,
    },
    {
      id: 131,
      name: "Saptaloka",
      series: "",
      price: "Rp ",
      category: "Acrylic on Canvas",
      artist: "Aura Paramaratri",
      dimension: "100 X 100 cm",
      years: "2023",
      image: "/images/products/saptalokac.png",
      isCart: false,
    },
    {
      id: 117,
      name: "Sabar",
      series: "",
      price: "Rp 16.250.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "100 X 150 cm",
      years: "2024",
      image: "/images/products/sabarc.png",
      isCart: false,
    },
    {
      id: 118,
      name: "Ikhlas",
      series: "",
      price: "Rp 37.500.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "100 X 150 cm",
      years: "2024",
      image: "/images/products/ikhlasc.png",
      isCart: false,
    },
    {
      id: 119,
      name: "Rela",
      series: "",
      price: "Rp 11.250.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "160 X 200 cm",
      years: "2024",
      image: "/images/products/relac.png",
      isCart: false,
    },
    {
      id: 120,
      name: "Tunduk",
      series: "",
      price: "Rp 31.250.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "160 X 200 cm",
      years: "2024",
      image: "/images/products/tundukc.png",
      isCart: false,
    },
    {
      id: 121,
      name: "Pasrah",
      series: "",
      price: "Rp 11.250.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "100 X 150 cm",
      years: "2024",
      image: "/images/products/pasrahc.png",
      isCart: false,
    },
    {
      id: 122,
      name: "Tulus",
      series: "",
      price: "Rp 16.250.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "100 X 150 cm",
      years: "2024",
      image: "/images/products/tulusc.png",
      isCart: false,
    },
    {
      id: 123,
      name: "Aku, Tuhan, dan Terang",
      series: "",
      price: "Rp 15.000.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "100 X 150 cm",
      years: "2024",
      image: "/images/products/attc.png",
      isCart: false,
    },
    {
      id: 124,
      name: "Aku, Tuhan, dan Gelap",
      series: "",
      price: "Rp 10.000.000",
      category: "Acrylic on Canvas",
      artist: "Alya Puspawati",
      dimension: "100 X 120 cm",
      years: "2024",
      image: "/images/products/atgc.png",
      isCart: false,
    },
    {
      id: 93,
      name: "Overlap",
      series: "",
      price: "Rp 2.500.000",
      category: "Oil on Canvas",
      artist: "Aurell Azzahra",
      dimension: "80 X 100 cm",
      years: "2024",
      image: "/images/products/overlap.png",
      isCart: false,
    },    
    {
      id: 94,
      name: "Jaga Mulut",
      series: "",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Kuroo",
      dimension: " cm",
      years: "2024",
      image: "/images/products/jaga_mulutc.png",
      isCart: false,
    },
    {
      id: 95,
      name: "Tubuh Delima",
      series: "",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Kuroo",
      dimension: " cm",
      years: "2024",
      image: "/images/products/tubuh_delimac.png",
      isCart: false,
    },    
    {
      id: 96,
      name: "The Will of Hope",
      series: "",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "80 X 100 cm",
      years: "",
      image: "/images/products/twohc.png",
      isCart: false,
    },
    {
      id: 97,
      name: "Lelayu:",
      series: "Bunga Tak Dikekang Malam",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "100 X 150 cm",
      years: "",
      image: "/images/products/lbtdmc.png",
      isCart: false,
    },
    {
      id: 98,
      name: "Lelayu:",
      series: "Tunduk Fajar",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "100 X 150 cm",
      years: "",
      image: "/images/products/ltfc.png",
      isCart: false,
    },
    {
      id: 99,
      name: "Lelayu:",
      series: "Lembayung Senja Baru",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "100 X 150 cm",
      years: "",
      image: "/images/products/llsbc.png",
      isCart: false,
    },
    {
      id: 100,
      name: "Bibit, Bebet, Bobot",
      series: "",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "80 X 80 cm",
      years: "",
      image: "/images/products/bbbc.png",
      isCart: false,
    },
    {
      id: 101,
      name: "Gnossienne:",
      series: "Relasi Dalam",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "80 X 100 cm",
      years: "",
      image: "/images/products/grdc.png",
      isCart: false,
    },
    {
      id: 102,
      name: "Lelayu:",
      series: "Sore Melayu",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "100 X 150 cm",
      years: "",
      image: "/images/products/lsmc.png",
      isCart: false,
    },
    {
      id: 103,
      name: "Lelayu:",
      series: "Riuh Siang",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "100 X 150 cm",
      years: "",
      image: "/images/products/lrsc.png",
      isCart: false,
    },
    {
      id: 104,
      name: "N w/ U",
      series: "",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "100 X 100 cm",
      years: "",
      image: "/images/products/nwuc.png",
      isCart: false,
    },
    {
      id: 105,
      name: "Lelayu:",
      series: "Lelayung Senja",
      price: "Rp ",
      category: "Oil on Canvas",
      artist: "Agnes",
      dimension: "100 X 150 cm",
      years: "",
      image: "/images/products/llsc.png",
      isCart: false,
    },
    {
      id: 106,
      name: "Mengalami Disharmoni 8.0584° S, 114.2433° E",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "244 X 144 cm",
      years: "2024",
      image: "/images/products/mdc.png",
      isCart: false,
    },
    {
      id: 107,
      name: "Mengalami Disharmoni 8.4166° N, 116.4666° E",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "244 X 144 cm",
      years: "2024",
      image: "/images/products/md2c.png",
      isCart: false,
    },
    {
      id: 108,
      name: "Mengalami Disharmoni 67.9680° N, 12.9645° E",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "244 X 144 cm",
      years: "2024",
      image: "/images/products/md3c.png",
      isCart: false,
    },
    {
      id: 109,
      name: "Choosing Priority",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "155 X 105 cm",
      years: "2023",
      image: "/images/products/cpc.png",
      isCart: false,
    },
    {
      id: 110,
      name: "Mengalami Disharmoni 7.3193° S, 107.7310° E",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "244 X 144 cm",
      years: "2024",
      image: "/images/products/md4c.png",
      isCart: false,
    },
    {
      id: 111,
      name: "Comfort in Apathy",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "155 X 105 cm",
      years: "2023",
      image: "/images/products/cac.png",
      isCart: false,
    },
    {
      id: 112,
      name: "I, an object",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: " cm",
      years: "",
      image: "/images/products/iaoc.png",
      isCart: false,
    },
    {
      id: 113,
      name: "Mengalami Disharmoni 8.0595° S, 114.2447° E",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "244 X 144 cm",
      years: "2024",
      image: "/images/products/md5c.png",
      isCart: false,
    },
    {
      id: 114,
      name: "Mengalami Disharmoni 67.9798° S, 12.9667° E",
      series: "",
      price: "Rp ",
      category: "Soft Pastels, Hard Pastels, and Charcoal on Paper",
      artist: "Khayla Indiva",
      dimension: "244 X 144 cm",
      years: "2024",
      image: "/images/products/md6c.png",
      isCart: false,
    },
    {
      id: 115,
      name: "Regrowth",
      series: "",
      price: "Rp 10.000.000",
      category: "Sculpture",
      artist: "Retno Airanissa",
      dimension: "75 X 90 cm",
      years: "",
      image: "/images/products/regrowthc.png",
      isCart: false,
    },
    {
      id: 116,
      name: "Dead Men Speak No Such Lies",
      series: "",
      price: "Rp 10.000.000",
      category: "Sculpture",
      artist: "Retno Airanissa",
      dimension: "40 X X 20 X 100 cm",
      years: "",
      image: "/images/products/dmsnslc.png",
      isCart: false,
    },
    {
      id: 88,
      name: "Harmonization",
      series: "",
      price: "Rp 5.000.000",
      category: "Soft Pastels on Paper",
      artist: "Ahmad Alighonyu",
      dimension: "117 X 78 cm",
      years: "2024",
      image: "/images/products/harmonizationc.png",
      isCart: false,
    },
    {
      id: 89,
      name: "Tautan Harmoni",
      series: "#1",
      price: "Rp 1.875.000",
      category: "Acrylic Ink on Paper",
      artist: "Ahmad Alighonyu",
      dimension: "41,5 X 51,5 cm",
      years: "2024",
      image: "/images/products/tautan_harmoni1c.png",
      isCart: false,
    },
    {
      id: 90,
      name: "Tautan Harmoni",
      series: "#2",
      price: "Rp 1.875.000",
      category: "Acrylic Ink on Paper",
      artist: "Ahmad Alighonyu",
      dimension: "41,5 X 51,5 cm",
      years: "2024",
      image: "/images/products/tautan_harmoni2c.png",
      isCart: false,
    },
    {
      id: 91,
      name: "Tautan Harmoni",
      series: "#3",
      price: "Rp 3.750.000",
      category: "Acrylic Ink on Paper",
      artist: "Ahmad Alighonyu",
      dimension: "50,5 X 58,5 cm",
      years: "2024",
      image: "/images/products/tautan_harmoni3c.png",
      isCart: false,
    },
    {
      id: 92,
      name: "Tautan Harmoni",
      series: "#4",
      price: "Rp 5.000.000",
      category: "Acrylic Ink on Paper",
      artist: "Ahmad Alighonyu",
      dimension: "80 X 86 cm",
      years: "2024",
      image: "/images/products/tautan_harmoni4c.png",
      isCart: false,
    },
    {
      id: 83,
      name: "Fuel for the Soul",
      series: "#1",
      price: "Rp 10.670.000",
      category: "Acrylic on Canvas",
      artist: "Sahda Ammarzia Wiedhayaka",
      dimension: "120 X 90 cm",
      years: "2024",
      image: "/images/products/ffts1c.png",
      isCart: false,
    },
    {
      id: 84,
      name: "Fuel for the Soul",
      series: "#2",
      price: "Rp 16.000.000",
      category: "Acrylic on Canvas",
      artist: "Sahda Ammarzia Wiedhayaka",
      dimension: "180 X 120 cm",
      years: "2024",
      image: "/images/products/ffts2c.png",
      isCart: false,
    },
    {
      id: 85,
      name: "Fuel for the Soul",
      series: "#3",
      price: "Rp 5.000.000",
      category: "Acrylic on Canvas",
      artist: "Sahda Ammarzia Wiedhayaka",
      dimension: "120 X 90 cm",
      years: "2024",
      image: "/images/products/ffts3c.png",
      isCart: false,
    },
    {
      id: 86,
      name: "Fuel for the Soul",
      series: "#4",
      price: "Rp 6.670.000",
      category: "Acrylic on Canvas",
      artist: "Sahda Ammarzia Wiedhayaka",
      dimension: "120 X 90 cm",
      years: "2024",
      image: "/images/products/ffts4c.png",
      isCart: false,
    },
    {
      id: 87,
      name: "Fuel for the Soul",
      series: "#5",
      price: "Rp 6.670.000",
      category: "Acrylic on Canvas",
      artist: "Sahda Ammarzia Wiedhayaka",
      dimension: "120 X 90 cm",
      years: "2024",
      image: "/images/products/ffts5c.png",
      isCart: false,
    },
    {
      id: 77,
      name: "Bodies",
      series: "",
      price: "Rp 7.330.000",
      category: "Soft Pastels on Paper",
      artist: "Flavia Giulietta",
      dimension: "14 X 20 cm per pieces",
      years: "2023",
      image: "/images/products/bodiesc.png",
      isCart: false,
    },
    {
      id: 78,
      name: "Back of Your Hand",
      series: "",
      price: "Rp 7.330.000",
      category: "Soft Pastels on Paper",
      artist: "Flavia Giulietta",
      dimension: "45,5 X 55,5 cm",
      years: "2023",
      image: "/images/products/boyhc.png",
      isCart: false,
    },
    {
      id: 79,
      name: "Clinging",
      series: "",
      price: "Rp 7.500.000",
      category: "Soft Pastels on Paper",
      artist: "Flavia Giulietta",
      dimension: "127 X 123 cm",
      years: "2024",
      image: "/images/products/clingingc.png",
      isCart: false,
    },
    {
      id: 80,
      name: "Adsorbsi",
      series: "",
      price: "Rp 8.500.000",
      category: "Soft Pastels on Paper",
      artist: "Flavia Giulietta",
      dimension: "135 X 105 cm",
      years: "2024",
      image: "/images/products/adsorbsic.png",
      isCart: false,
    },
    {
      id: 81,
      name: "Aksi",
      series: "",
      price: "Rp 8.500.000",
      category: "Soft Pastels on Paper",
      artist: "Flavia Giulietta",
      dimension: "122 X 123 cm",
      years: "2024",
      image: "/images/products/aksic.png",
      isCart: false,
    },
    {
      id: 82,
      name: "Afeksi",
      series: "",
      price: "Rp 8.500.000",
      category: "Soft Pastels on Paper",
      artist: "Flavia Giulietta",
      dimension: "100 X 150 cm",
      years: "2024",
      image: "/images/products/afeksic.png",
      isCart: false,
    },
    {
      id: 72,
      name: "Heiwa",
      series: "",
      price: "Rp 6.670.000",
      category: "Acrylic and Ink on Canvas",
      artist: "Meitiara Diantha",
      dimension: "110 X 110 cm",
      years: "2023",
      image: "/images/products/heiwac.png",
      isCart: false,
    },
    {
      id: 73,
      name: "Spirit Ascending",
      series: "",
      price: "Rp 10.670.000",
      category: "Acrylic and Ink on Canvas",
      artist: "Meitiara Diantha",
      dimension: "239 X 120 cm",
      years: "2023",
      image: "/images/products/spirit_ascendingc.png",
      isCart: false,
    },
    {
      id: 74,
      name: "Tears",
      series: "",
      price: "Rp 8.000.000",
      category: "Acrylic and Ink on Canvas",
      artist: "Meitiara Diantha",
      dimension: "100 X 100 cm",
      years: "2024",
      image: "/images/products/tearsc.png",
      isCart: false,
    },
    {
      id: 75,
      name: "Apocalypse",
      series: "",
      price: "Rp 6.670.000",
      category: "Acrylic and Ink on Canvas",
      artist: "Meitiara Diantha",
      dimension: "100 X 100 cm",
      years: "2024",
      image: "/images/products/apocalypsec.png",
      isCart: false,
    },
    {
      id: 76,
      name: "Paprika?",
      series: "",
      price: "Rp 6.670.000",
      category: "Acrylic and Ink on Canvas",
      artist: "Meitiara Diantha",
      dimension: "75 X 100 cm",
      years: "2024",
      image: "/images/products/paprikac.png",
      isCart: false,
    },
    {
      id: 59,
      name: "Bentang Halimun",
      series: "#1",
      price: "Rp 11.300.000",
      category: "Charcoal on Paper",
      artist: "Kadek Bagus Wedanta Yogananda",
      dimension: "146 X 96 cm",
      years: "2024",
      image: "/images/products/bentang_halimun1c.png",
      isCart: false,
    },
    {
      id: 60,
      name: "Bentang Halimun",
      series: "#2",
      price: "Rp 11.300.000",
      category: "Charcoal on Paper",
      artist: "Kadek Bagus Wedanta Yogananda",
      dimension: "146 X 96 cm",
      years: "2024",
      image: "/images/products/bentang_halimun2c.png",
      isCart: false,
    },
    {
      id: 61,
      name: "Bentang Halimun",
      series: "#3",
      price: "Rp 11.300.000",
      category: "Charcoal on Paper",
      artist: "Kadek Bagus Wedanta Yogananda",
      dimension: "146 X 96 cm",
      years: "2024",
      image: "/images/products/bentang_halimun3c.png",
      isCart: false,
    },
    {
      id: 62,
      name: "Hududdha",
      series: "",
      price: "Rp 11.300.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112 cm",
      years: "2024",
      image: "/images/products/hududdhac.png",
      isCart: false,
    },    
    {
      id: 63,
      name: "Jijnasu",
      series: "",
      price: "Rp 12.000.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112cm",
      years: "2024",
      image: "/images/products/jijnasuc.png",
      isCart: false,
    },    
    {
      id: 64,
      name: "Dipaeka",
      series: "",
      price: "Rp 12.000.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112cm",
      years: "2024",
      image: "/images/products/dipaekac.png",
      isCart: false,
    },    
    {
      id: 65,
      name: "Dhire",
      series: "",
      price: "Rp 12.000.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112cm",
      years: "2024",
      image: "/images/products/dhirec.png",
      isCart: false,
    },    
    {
      id: 66,
      name: "Agnitara",
      series: "",
      price: "Rp 12.000.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112 cm",
      years: "2024",
      image: "/images/products/agnitarac.png",
      isCart: false,
    },
    {
      id: 67,
      name: "Varuga Hana",
      series: "",
      price: "Rp 12.530.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "71 X 98 cm",
      years: "2024",
      image: "/images/products/varuga_hanac.png",
      isCart: false,
    },
    {
      id: 68,
      name: "Mahadurga",
      series: "",
      price: "Rp 12.530.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112 cm",
      years: "2024",
      image: "/images/products/mahadurgac.png",
      isCart: false,
    },
    {
      id: 69,
      name: "Parvakaro",
      series: "",
      price: "Rp 12.530.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112 cm",
      years: "2024",
      image: "/images/products/parvakaroc.png",
      isCart: false,
    },
    {
      id: 70,
      name: "Aglonyx",
      series: "",
      price: "Rp 12.000.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "79 X 109 cm",
      years: "2024",
      image: "/images/products/aglonyxc.png",
      isCart: false,
    },
    {
      id: 71,
      name: "Vandriya",
      series: "",
      price: "Rp 12.000.000",
      category: "Ballpoint on Paper",
      artist: "Mushoffa Nabiel Rizqullah",
      dimension: "82 X 112 cm",
      years: "2024",
      image: "/images/products/vandriyac.png",
      isCart: false,
    },
    {
      id: 24,
      name: "Modern Skinwalkers",
      series: "#1",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2024",
      image: "/images/products/pig_maestroc.png",
      isCart: false,
    },
    {
      id: 25,
      name: "Modern Skinwalkers",
      series: "#2",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2024",
      image: "/images/products/frog_bicyclingc.png",
      isCart: false,
    },
    {
      id: 26,
      name: "Modern Skinwalkers",
      series: "#3",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2024",
      image: "/images/products/cow_readingc.png",
      isCart: false,
    },
    {
      id: 27,
      name: "Modern Skinwalkers",
      series: "#4",
      price: "Rp 4.000.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "55 X 75 cm",
      years: "2024",
      image: "/images/products/pig_moneyc.png",
      isCart: false,
    },
    {
      id: 28,
      name: "Modern Skinwalkers",
      series: "#5",
      price: "Rp 4.000.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "75 X 55 cm",
      years: "2024",
      image: "/images/products/horse_sideviewc.png",
      isCart: false,
    },
    {
      id: 29,
      name: "Modern Skinwalkers",
      series: "#6",
      price: "Rp 4.000.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "75 X 55 cm",
      years: "2024",
      image: "/images/products/bull_sitc.png",
      isCart: false,
    },
    {
      id: 30,
      name: "Could be Us?",
      series: "#1",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/smoking_birdc.png",
      isCart: false,
    },
    {
      id: 31,
      name: "Could be Us?",
      series: "#2",
      price: "Rp 677.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/elephant_toiletc.png",
      isCart: false,
    },
    {
      id: 32,
      name: "Could be Us?",
      series: "#3",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/singing_pigc.png",
      isCart: false,
    },
    {
      id: 33,
      name: "Could be Us?",
      series: "#4",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/walking_catc.png",
      isCart: false,
    },
    {
      id: 34,
      name: "Could be Us?",
      series: "#5",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/rhino_standingc.png",
      isCart: false,
    },
    {
      id: 35,
      name: "Could be Us?",
      series: "#6",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/monk_monkeyc.png",
      isCart: false,
    },
    {
      id: 36,
      name: "Could be Us?",
      series: "#7",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/kid_catc.png",
      isCart: false,
    },
    {
      id: 37,
      name: "Could be Us?",
      series: "#8",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/sitting_zebrac.png",
      isCart: false,
    },
    {
      id: 38,
      name: "Could be Us?",
      series: "#9",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/smoking_bird_3c.png",
      isCart: false,
    },
    {
      id: 39,
      name: "Could be Us?",
      series: "#10",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/thinking_fishc.png",
      isCart: false,
    },
    {
      id: 40,
      name: "Could be Us?",
      series: "#11",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/smoking_bird_2c.png",
      isCart: false,
    },
    {
      id: 41,
      name: "Could be Us?",
      series: "#12",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/bear_toiletc.png",
      isCart: false,
    },
    {
      id: 42,
      name: "Could be Us?",
      series: "#13",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "29 X 21 cm",
      years: "2024",
      image: "/images/products/iguana_bicyclingc.png",
      isCart: false,
    },
    {
      id: 43,
      name: "Could be Us?",
      series: "#14",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/fat_bearc.png",
      isCart: false,
    },
    {
      id: 44,
      name: "Could be Us?",
      series: "#15",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/cat_eatingc.png",
      isCart: false,
    },
    {
      id: 45,
      name: "Could be Us?",
      series: "#16",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/smoking_catc.png",
      isCart: false,
    },
    {
      id: 46,
      name: "Could be Us?",
      series: "#17",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/sloth_toiletc.png",
      isCart: false,
    },
    {
      id: 47,
      name: "Could be Us?",
      series: "#18",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/cooking_wolfc.png",
      isCart: false,
    },
    {
      id: 48,
      name: "Could be Us?",
      series: "#19",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/dog_toiletc.png",
      isCart: false,
    },
    {
      id: 49,
      name: "Could be Us?",
      series: "#20",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21 X 29 cm",
      years: "2024",
      image: "/images/products/cat_tuxedoc.png",
      isCart: false,
    },
    {
      id: 50,
      name: "Should I fancy you?",
      series: "#1",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50 X 50 cm",
      years: "2024",
      image: "/images/products/headshot_pigc.png",
      isCart: false,
    },
    {
      id: 51,
      name: "Should I fancy you?",
      series: "#2",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50 X 50 cm",
      years: "2024",
      image: "/images/products/headshot_chickenc.png",
      isCart: false,
    },
    {
      id: 52,
      name: "Should I fancy you?",
      series: "#3",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50 X 50 cm",
      years: "2024",
      image: "/images/products/headshot_catc.png",
      isCart: false,
    },
    {
      id: 53,
      name: "Should I fancy you?",
      series: "#4",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50 X 50 cm",
      years: "2024",
      image: "/images/products/headshot_horsec.png",
      isCart: false,
    },
    {
      id: 54,
      name: "Should I fancy you?",
      series: "#5",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50 X 50 cm",
      years: "2024",
      image: "/images/products/headshot_birdc.png",
      isCart: false,
    },
    {
      id: 55,
      name: "Should I fancy you?",
      series: "#6",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50 X 50 cm",
      years: "2024",
      image: "/images/products/headshot_slothc.png",
      isCart: false,
    },
    {
      id: 56,
      name: "It's Tough Nowadays",
      series: "",
      price: "Rp 9.340.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "90 X 140 cm",
      years: "2024",
      image: "/images/products/dog_drinkingc.png",
      isCart: false,
    },
    {
      id: 57,
      name: "Melodic Companion",
      series: "",
      price: "Rp 6.670.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "100 X 100 cm",
      years: "2024",
      image: "/images/products/sax_cat.png",
      isCart: false,
    },
    {
      id: 58,
      name: "True Delicacy",
      series: "",
      price: "Rp 8.170.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "85 X 135 cm",
      years: "2024",
      image: "/images/products/orchestra_pigc.png",
      isCart: false,
    },
    {
      id: 1,
      name: "Hand to Hand",
      series: "#1",
      price: "Rp 534.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "140 X 90 cm",
      years: "2023",
      image: "/images/products/handtohandseries1c.png",
      isCart: false,
    },
    {
      id: 2,
      name: "Hand to Hand",
      series: "#2",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2023",
      image: "/images/products/handtohandseries2c.png",
      isCart: false,
    },
    {
      id: 3,
      name: "Hand to Hand",
      series: "#3",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2023",
      image: "/images/products/handtohandseries3c.png",
      isCart: false,
    },
    {
      id: 4,
      name: "Hand to Hand",
      series: "#4",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2023",
      image: "/images/products/handtohandseries4c.png",
      isCart: false,
    },
    {
      id: 5,
      name: "Hand to Hand",
      series: "#5",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2023",
      image: "/images/products/handtohandseries5c.png",
      isCart: false,
    },
    {
      id: 6,
      name: "Hand to Hand",
      series: "#6",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2023",
      image: "/images/products/handtohandseries6c.png",
      isCart: false,
    },
    {
      id: 7,
      name: "Hand to Hand",
      series: "#7",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2023",
      image: "/images/products/handtohandseries7c.png",
      isCart: false,
    },
    {
      id: 8,
      name: "Hand to Hand",
      series: "#8",
      price: "Rp 240.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40 X 40 cm",
      years: "2023",
      image: "/images/products/handtohandseries8c.png",
      isCart: false,
    },
    {
      id: 9,
      name: "Hand to Hand",
      series: "#9",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries9c.png",
      isCart: false,
    },{
      id: 10,
      name: "Hand to Hand",
      series: "#10",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries10c.png",
      isCart: false,
    },{
      id: 11,
      name: "Hand to Hand",
      series: "#11",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries11c.png",
      isCart: false,
    },{
      id: 12,
      name: "Hand to Hand",
      series: "H#12",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries12c.png",
      isCart: false,
    },{
      id: 13,
      name: "Hand to Hand",
      series: "#13",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries13c.png",
      isCart: false,
    },{
      id: 14,
      name: "Hand to Hand",
      series: "#14",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries14c.png",
      isCart: false,
    },{
      id: 15,
      name: "Hand to Hand",
      series: "#15",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries15c.png",
      isCart: false,
    },{
      id: 16,
      name: "Hand to Hand",
      series: "#16",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries16c.png",
      isCart: false,
    },{
      id: 17,
      name: "Hand to Hand",
      series: "#17",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries17c.png",
      isCart: false,
    },
    {
      id: 18,
      name: "Hand to Hand",
      series: "#18",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries18c.png",
      isCart: false,
    },
    {
      id: 19,
      name: "Hand to Hand",
      series: "#19",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries19c.png",
      isCart: false,
    },
    {
      id: 20,
      name: "Hand to Hand",
      series: "#20",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries20c.png",
      isCart: false,
    },
    {
      id: 21,
      name: "Hand to Hand",
      series: "#21",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries21c.png",
      isCart: false,
    },
    {
      id: 22,
      name: "Hand to Hand",
      series: "#22",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries22c.png",
      isCart: false,
    },
    {
      id: 23,
      name: "Hand to Hand",
      series: "#23",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries23c.png",
      isCart: false,
    },
  ];