export const products = [
    {
      id: 24,
      name: "Modern Skinwalkers",
      series: "#1",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2024",
      image: "/images/products/pig_maestro.png",
      isCart: false,
    },
    {
      id: 25,
      name: "Modern Skinwalkers",
      series: "#2",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2024",
      image: "/images/products/frog_bicycling.png",
      isCart: false,
    },
    {
      id: 26,
      name: "Modern Skinwalkers",
      series: "#3",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2024",
      image: "/images/products/cow_reading.png",
      isCart: false,
    },
    {
      id: 27,
      name: "Modern Skinwalkers",
      series: "#4",
      price: "Rp 4.000.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "55X75cm",
      years: "2024",
      image: "/images/products/pig_money.png",
      isCart: false,
    },
    {
      id: 28,
      name: "Modern Skinwalkers",
      series: "#5",
      price: "Rp 4.000.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "75X55cm",
      years: "2024",
      image: "/images/products/horse_sideview.png",
      isCart: false,
    },
    {
      id: 29,
      name: "Modern Skinwalkers",
      series: "#6",
      price: "Rp 4.000.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "75X55cm",
      years: "2024",
      image: "/images/products/bull_sit.png",
      isCart: false,
    },
    {
      id: 30,
      name: "Could be Us?",
      series: "#1",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/smoking_bird.png",
      isCart: false,
    },
    {
      id: 31,
      name: "Could be Us?",
      series: "#2",
      price: "Rp 677.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/elephant_on_the_toilet.png",
      isCart: false,
    },
    {
      id: 32,
      name: "Could be Us?",
      series: "#3",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/singing_pig.png",
      isCart: false,
    },
    {
      id: 33,
      name: "Could be Us?",
      series: "#4",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/walking_cat.png",
      isCart: false,
    },
    {
      id: 34,
      name: "Could be Us?",
      series: "#5",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/rhino_standing.png",
      isCart: false,
    },
    {
      id: 35,
      name: "Could be Us?",
      series: "#6",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/monk_monkey.png",
      isCart: false,
    },
    {
      id: 36,
      name: "Could be Us?",
      series: "#7",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/kid_cat.png",
      isCart: false,
    },
    {
      id: 37,
      name: "Could be Us?",
      series: "#8",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/sitting_zebra.png",
      isCart: false,
    },
    {
      id: 38,
      name: "Could be Us?",
      series: "#9",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/smoking_bird_3.png",
      isCart: false,
    },
    {
      id: 39,
      name: "Could be Us?",
      series: "#10",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/thinking_fish.png",
      isCart: false,
    },
    {
      id: 40,
      name: "Could be Us?",
      series: "#11",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/smoking_bird_2.png",
      isCart: false,
    },
    {
      id: 41,
      name: "Could be Us?",
      series: "#12",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/bear_on_the_toilet.png",
      isCart: false,
    },
    {
      id: 42,
      name: "Could be Us?",
      series: "#13",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "29X21cm",
      years: "2024",
      image: "/images/products/iguana_bicycling.png",
      isCart: false,
    },
    {
      id: 43,
      name: "Could be Us?",
      series: "#14",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/fat_bear.png",
      isCart: false,
    },
    {
      id: 44,
      name: "Could be Us?",
      series: "#15",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/cat_eating_banana.png",
      isCart: false,
    },
    {
      id: 45,
      name: "Could be Us?",
      series: "#16",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/smoking_cat.png",
      isCart: false,
    },
    {
      id: 46,
      name: "Could be Us?",
      series: "#17",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/sloth_on_the_toilet.png",
      isCart: false,
    },
    {
      id: 47,
      name: "Could be Us?",
      series: "#18",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/cooking_wolf.png",
      isCart: false,
    },
    {
      id: 48,
      name: "Could be Us?",
      series: "#19",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/dog_on_the_toilet.png",
      isCart: false,
    },
    {
      id: 49,
      name: "Could be Us?",
      series: "#20",
      price: "Rp 667.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "21X29cm",
      years: "2024",
      image: "/images/products/cat_in_tuxedo.png",
      isCart: false,
    },
    {
      id: 50,
      name: "Should I fancy you?",
      series: "#1",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50X50cm",
      years: "2024",
      image: "/images/products/headshot_pig.png",
      isCart: false,
    },
    {
      id: 51,
      name: "Should I fancy you?",
      series: "#2",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50X50cm",
      years: "2024",
      image: "/images/products/headshot_chicken.png",
      isCart: false,
    },
    {
      id: 52,
      name: "Should I fancy you?",
      series: "#3",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50X50cm",
      years: "2024",
      image: "/images/products/headshot_cat.png",
      isCart: false,
    },
    {
      id: 53,
      name: "Should I fancy you?",
      series: "#4",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50X50cm",
      years: "2024",
      image: "/images/products/headshot_horse.png",
      isCart: false,
    },
    {
      id: 54,
      name: "Should I fancy you?",
      series: "#5",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50X50cm",
      years: "2024",
      image: "/images/products/headshot_bird.png",
      isCart: false,
    },
    {
      id: 55,
      name: "Should I fancy you?",
      series: "#6",
      price: "Rp 800.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "50X50cm",
      years: "2024",
      image: "/images/products/headshot_sloth.png",
      isCart: false,
    },
    {
      id: 56,
      name: "It's Tough Nowadays",
      series: "",
      price: "Rp 9.340.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "90X140cm",
      years: "2024",
      image: "/images/products/dog_drinking.png",
      isCart: false,
    },
    {
      id: 55,
      name: "Melodic Companion",
      series: "",
      price: "Rp 6.670.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "100X100cm",
      years: "2024",
      image: "/images/products/sax_cat.png",
      isCart: false,
    },
    {
      id: 55,
      name: "True Delicacy",
      series: "",
      price: "Rp 8.170.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "85X135cm",
      years: "2024",
      image: "/images/products/orchestra_pig.jpg",
      isCart: false,
    },
    {
      id: 1,
      name: "Hand to Hand",
      series: "#1",
      price: "Rp 534.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "140X90cm",
      years: "2023",
      image: "/images/products/handtohandseries1.jpg",
      isCart: false,
    },
    {
      id: 2,
      name: "Hand to Hand",
      series: "#2",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries2.jpg",
      isCart: false,
    },
    {
      id: 3,
      name: "Hand to Hand",
      series: "#3",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries3.jpg",
      isCart: false,
    },
    {
      id: 4,
      name: "Hand to Hand",
      series: "#4",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries4.jpg",
      isCart: false,
    },
    {
      id: 5,
      name: "Hand to Hand",
      series: "#5",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries5.jpg",
      isCart: false,
    },
    {
      id: 6,
      name: "Hand to Hand",
      series: "#6",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries6.jpg",
      isCart: false,
    },
    {
      id: 7,
      name: "Hand to Hand",
      series: "#7",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries7.jpg",
      isCart: false,
    },
    {
      id: 8,
      name: "Hand to Hand",
      series: "#8",
      price: "Rp 240.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries8.jpg",
      isCart: false,
    },
    {
      id: 9,
      name: "Hand to Hand",
      series: "#9",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries9.jpg",
      isCart: false,
    },{
      id: 10,
      name: "Hand to Hand",
      series: "#10",
      price: "Rp 2.400.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries10.jpg",
      isCart: false,
    },{
      id: 11,
      name: "Hand to Hand",
      series: "#11",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries11.jpg",
      isCart: false,
    },{
      id: 12,
      name: "Hand to Hand",
      series: "H#12",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries12.jpg",
      isCart: false,
    },{
      id: 13,
      name: "Hand to Hand",
      series: "#13",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries13.jpg",
      isCart: false,
    },{
      id: 14,
      name: "Hand to Hand",
      series: "#14",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries14.jpg",
      isCart: false,
    },{
      id: 15,
      name: "Hand to Hand",
      series: "#15",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries15.png",
      isCart: false,
    },{
      id: 16,
      name: "Hand to Hand",
      series: "#16",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries16.jpg",
      isCart: false,
    },{
      id: 17,
      name: "Hand to Hand",
      series: "#17",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries17.jpg",
      isCart: false,
    },
    {
      id: 18,
      name: "Hand to Hand",
      series: "#18",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries18.jpg",
      isCart: false,
    },
    {
      id: 19,
      name: "Hand to Hand",
      series: "#19",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries19.jpg",
      isCart: false,
    },
    {
      id: 20,
      name: "Hand to Hand",
      series: "#20",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries20.jpg",
      isCart: false,
    },
    {
      id: 21,
      name: "Hand to Hand",
      series: "#21",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries21.jpg",
      isCart: false,
    },
    {
      id: 22,
      name: "Hand to Hand",
      series: "#22",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries22.jpg",
      isCart: false,
    },
    {
      id: 23,
      name: "Hand to Hand",
      series: "#23",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries23.jpg",
      isCart: false,
    },
  ];