export const products = [
    {
      id: 1,
      name: "#1",
      series: "Hand to Hand",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "140X90cm",
      years: "2023",
      image: "/images/products/handtohandseries1.jpg",
      isCart: false,
    },
    {
      id: 2,
      name: "#2",
      series: "Hand to Hand",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries2.jpg",
      isCart: false,
    },
    {
      id: 3,
      name: "#3",
      series: "Hand to Hand",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries3.jpg",
      isCart: false,
    },
    {
      id: 4,
      name: "#4",
      series: "Hand to Hand",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries4.jpg",
      isCart: false,
    },
    {
      id: 5,
      name: "#5",
      series: "Hand to Hand",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries5.jpg",
      isCart: false,
    },
    {
      id: 6,
      name: "#6",
      series: "Hand to Hand",
      price: "Rp 550.000",
      category: "Watercolor",
      artist: "Auditama Nugraha",
      dimension: "40X40cm",
      years: "2023",
      image: "/images/products/handtohandseries6.jpg",
      isCart: false,
    }
  ];